// this const are examples that usually come from some api for example

export const drivers = [
  { id: 1, name: "Driver 1", color: "pink" },
  { id: 2, name: "Driver 2", color: "lightblue" },
  { id: 3, name: "Driver 3", color: "yellow" },
  { id: 4, name: "Driver 4", color: "lightgreen" },
  { id: 5, name: "Driver 5", color: "violet" },
]

export const deliveryLocations = [
  {
    id: 1,
    lat: -34.921318,
    lng: -57.953415,
    assignedTo: 1,
    direction: "la plata calle 51 123456",
  },
  {
    id: 2,
    lat: -34.921318,
    lng: -57.9536,
    assignedTo: null,
    direction: "la plata calle 56 123456",
  },
  {
    id: 3,
    lat: -34.920315,
    lng: -57.951475,
    assignedTo: null,
    direction: "C. 11 1028",
  },
  {
    id: 4,
    lat: -34.922215,
    lng: -57.951153,
    assignedTo: null,
    direction: "C. 12 1150-1100",
  },
  {
    id: 5,
    lat: -34.9232,
    lng: -57.952355,
    assignedTo: null,
    direction: "Av. 13 1115",
  },
  {
    id: 6,
    lat: -34.918766,
    lng: -57.956754,
    assignedTo: null,
    direction: "C. 48 867",
  },
  {
    id: 7,
    lat: -34.919523,
    lng: -57.952591,
    assignedTo: null,
    direction: "Uni De Periodismo",
  },
  {
    id: 8,
    lat: -34.923394,
    lng: -57.956625,
    assignedTo: null,
    direction: "C. 15 989",
  },
  //   {
  //     id: 9,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 10,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 11,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 12,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 13,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 14,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 15,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 16,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 17,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 18,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 19,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
  //   {
  //     id: 20,
  //     lat: ,
  //     lng: ,
  //     assignedTo: null,
  //     direction: "",
  //   },
]
